# Slowness of Loops

In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
big_array = np.random.randint(1,100, size=1000000)
%timeit compute_reciprocals(big_array)

6.66 s ± 378 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


This seems really SLOW!!! Most of times are wasted doing type checks... What if we have something that are all of fixed type??

In [4]:
print("Compute reciprocals using List and for loop: " ,compute_reciprocals(values))
print("Compute reciprocals using universal function: ", 1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [3]:
%timeit (1.0 / big_array)

9.22 ms ± 498 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


And it is very flexible, we can try to operate between two arrays:

In [5]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In 2-d array as well:

In [7]:
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

# Explore NumPy's UFuncs

## Array arithmetic

In [9]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


## Absolute value

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
np.abs(x)

## Trig Functions

In [ ]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

In [10]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


## Exponentials and Logarithms

In [ ]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

In [ ]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

## Aggregates

*Reduce* method repeated applies a give noperation to the elements of an array until only a single result remains

In [11]:
x = np.arange(1,6)
np.add.reduce(x)

15

*accumulate* store all the intermediate results of the computation

In [12]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [14]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b

In [15]:
vfunc = np.vectorize(myfunc)
vfunc([1,2,3,4],2)

array([3, 4, 1, 2])

In [23]:
largeArr = np.random.randint(0,2,1000000)
%timeit vfunc(largeArr,1)

325 ms ± 24.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [26]:
def runLoop(num):
    rst = []
    for i in largeArr:
        rst.append(myfunc(i,1))
    return rst

In [27]:
%timeit runLoop(0.5)

1.58 s ± 87.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [22]:
largeArr

array([0, 0, 0, ..., 0, 0, 0])